import { expect, test } from "@playwright/test";
import { openApp } from "./addList.helpers";
test("calendar owns sharing and subscriptions, with keyboard-safe dialogs", async ({ page }, info) => {
  await openApp(page);
  await page.goto("/calendar");
  const options = page.getByRole("button", { name: "View options", exact: true });
  await options.click();
  const share = page.getByRole("button", { name: "Share", exact: true });
  await share.click();
  await expect(page.getByRole("dialog", { name: "Share", exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.screenshot({ path: info.outputPath("share.png") });
  await page.keyboard.press("Escape");
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await expect(options).toBeFocused();
  await options.click();
  await page.getByRole("button", { name: "Calendars", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Calendars", exact: true });
  await expect(dialog).toBeVisible();
  await dialog.getByRole("button", { name: /add/i }).first().click();
  await expect(dialog.locator("input").first()).toBeVisible();
  expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true);
  await page.screenshot({ path: info.outputPath("subscriptions.png") });
  await page.keyboard.press("Escape");
  await page.goto("/settings");
  const compact = page.locator(".ff-settings-mobile-nav select");
  if (await compact.isVisible()) await compact.selectOption("connections");
  else await page.getByRole("tab", { name: "Connections", exact: true }).click();
  await expect(page.locator(".ff-settings-content > .ff-cal-settings-stack > section")).toHaveCount(1);
});
